# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385f7d2d8c783ee576e0a83a719b7f69fb48dea0aa42d224c61c1c1dea6cea33074af727e712081fbba6274b3a401ce8dcc1f9367d1e1c46183a68e9c42ffbbb

test:
  secret_key_base: 486b67658417903d5b7d08d1f8e4e935871ed3cbec4462b2360fb73be467f0a88a32a9ca17a67f0d84cbbe5a7092388c68cd1fa7bef811892a4baf28b5d4f802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
